function Hd = FIR_Least_squares_Filter
%FIR_LEAST_SQUARES_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.12 and DSP System Toolbox 9.14.
% Generated on: 08-Dec-2022 12:52:11

% FIR least-squares Bandpass filter designed using the FIRLS function.

% All frequency values are in Hz.
Fs = 250;  % Sampling Frequency

N      = 200;  % Order
Fstop1 = 0.5;  % First Stopband Frequency
Fpass1 = 1;    % First Passband Frequency
Fpass2 = 20;   % Second Passband Frequency
Fstop2 = 21;   % Second Stopband Frequency
Wstop1 = 80;   % First Stopband Weight
Wpass  = 50;   % Passband Weight
Wstop2 = 20;   % Second Stopband Weight

% Calculate the coefficients using the FIRLS function.
b  = firls(N, [0 Fstop1 Fpass1 Fpass2 Fstop2 Fs/2]/(Fs/2), [0 0 1 1 0 ...
           0], [Wstop1 Wpass Wstop2]);
Hd = dfilt.dffir(b);

% [EOF]
