function Hd = FIR_Window_Bartlett_Hanning_Filter
%FIR_WINDOW_BARTLETT_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.12 and DSP System Toolbox 9.14.
% Generated on: 08-Dec-2022 17:37:03

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 250;  % Sampling Frequency

N    = 50;       % Order
Fc1  = 1;        % First Cutoff Frequency
Fc2  = 20;       % Second Cutoff Frequency
flag = 'scale';  % Sampling Flag
% Create the window vector for the design algorithm.
win = barthannwin(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, [Fc1 Fc2]/(Fs/2), 'bandpass', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
