function Hd = IIR_Elliptic_Filter
%IIR_ELLIPTIC_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.12 and DSP System Toolbox 9.14.
% Generated on: 08-Dec-2022 13:27:38

% Elliptic Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 250;  % Sampling Frequency

Fstop1 = 0.5;     % First Stopband Frequency
Fpass1 = 1;       % First Passband Frequency
Fpass2 = 20;      % Second Passband Frequency
Fstop2 = 20.5;    % Second Stopband Frequency
Astop1 = 40;      % First Stopband Attenuation (dB)
Apass  = 1;       % Passband Ripple (dB)
Astop2 = 40;      % Second Stopband Attenuation (dB)
match  = 'both';  % Band to match exactly

% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, ...
                      Astop2, Fs);
Hd = design(h, 'ellip', 'MatchExactly', match);

% [EOF]
